### ISSUE TITLE
大佬能看看吗？启动后打开报错

### ISSUE THREAD

**Issue by 0k-1** [feng19/x_trace#1]
erlang 25 elixir1.14
![image](https://github.com/feng19/x_trace/assets/61181198/b465fd63-20f1-4a3a-adad-1561ac8f03a6)

![image](https://github.com/feng19/x_trace/assets/61181198/730d7bb7-c905-46bd-b82d-2de8e5ea6a4d)

![image](https://github.com/feng19/x_trace/assets/61181198/f62fba61-b518-4f1e-b343-a250fbcec1fc)

**Comment by feng19** [comment]
https://github.com/feng19/x_trace/commit/9dcbe4ad0f7185b9b8d5680999a6556500d6c26e

最新的提交已经修复了这个问题，谢谢反馈
